DROP TABLE IF EXISTS Count;
CREATE TABLE IF NOT EXISTS Count (Value INTEGER DEFAULT 0);
DROP TABLE IF EXISTS History;
CREATE TABLE IF NOT EXISTS History (Key TEXT PRIMARY KEY, Timestamp INTEGER DEFAULT 0);
